### ISSUE TITLE
NavBar designen

### ISSUE THREAD

**Issue by StefanLoeffelholz** [kit-recipe-app/front-end#11]
Design der App-Navigation-Bar und festlegen eines Designs
Bestandteile: 

- [x] Icons
- [x] Anordnung der Icons
- [ ] Farbe
- [ ] Farbe des ausgewählten Icon

**Comment by yalllah** [comment]
![Image](https://user-images.githubusercontent.com/91542926/205509612-556384d7-cbbf-4f05-94e3-df55b8bfc4cf.png)

**Comment by yalllah** [comment]
![Image](https://user-images.githubusercontent.com/91542926/205510234-07185e74-b143-4073-9b4f-f2c6476ff855.png)
