### ISSUE TITLE
Rezeptübersicht designen

### ISSUE THREAD

**Issue by StefanLoeffelholz** [kit-recipe-app/front-end#12]
Die Übersicht der verschiedenen Rezepte muss fertig sein.
Bestandteile die fertig sein müssen: 

- [x] Objekt was ein Rezept darstellt
- [x] Favoriten-Sektion/Favoriten-Button
- [x] Suchleisten/Filter-Funktion(Button)
- [x] Vorschlag-Sektion; kürzlich dafür eingekauft Sektion/Button
- [x] eigene Rezepte Button -> Übersicht der eigenen Rezepte

Bestandteile, die nicht dazu gehören: Navigation Bar, Header

**Comment by yalllah** [comment]
![Image](https://user-images.githubusercontent.com/91542926/204324283-557601f0-2693-4661-b991-b6f3e48be343.png)

**Comment by StefanLoeffelholz** [comment]
![Image](https://user-images.githubusercontent.com/117743469/205299036-0e3151e9-c1f6-44e9-980c-5b334f4ed018.png)
