### ISSUE TITLE
Rezept designen

### ISSUE THREAD

**Issue by StefanLoeffelholz** [kit-recipe-app/front-end#15]
Eine Vorlage, wie die Rezepte aufgebaut sind muss fertig sein.
Bestandteile die fertig sein müssen:

- [ ] Bild, welches das gekochte Gericht darstellt
- [ ] Name des Gerichts
- [ ] Darstellung der Zutaten
- [ ] Button der mich die Zutaten zu einer Einkaufsliste hinzufügen lässt
- [ ] Darstellung der einzelnen Schritte beim Kochen(ggf. Bild bei jedem Schritt hinzufügen)
- [ ] kurze Beschreibung des Gerichts
- [ ] Übersicht über Schwierigkeit, Dauer, ggf. Kcal des Gerichts
- [ ] Anzeige, ob das Gericht gespeichert ist + Button zum speichern des Gerichts

Bestandteile, die nicht dazu gehören: Navigation Bar, Header

**Comment by yalllah** [comment]
Interactive Surround-Button (Button mit Funktionalitäten wie "Rezept zu Einkaufsliste hinzufügen", "Rezept zu Liste hinzufügen", "Rezept teilen", etc.)
